# -*- coding: utf-8 -*-
"""Project_notebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gGA6BhXeh4wM8pW4kfYF_AfTRB1Q70s5

# 📊 HR Analytics – Employee Attrition & Income Analysis

Dataset Description
This dataset includes employee information such as department, salary, experience level, and involvement in R&D. It can be used to explore workforce trends, compare departments, and generate insights.
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


df=pd.read_csv('/content/HR Employee Attrition.csv')
df.head()

df.shape

df.describe()

df.info()

"""

# 🧹 1) Data Cleaning

Removing outliers from Monthly Income using the 5%–95% clipping."""

df.boxplot(column='MonthlyIncome', figsize=(15,5))

# Clean MonthlyIncome outliers
lower = df['MonthlyIncome'].quantile(0.05)
upper = df['MonthlyIncome'].quantile(0.95)
df['MonthlyIncome'] = df['MonthlyIncome'].clip(lower, upper)

df.boxplot(column='MonthlyIncome', figsize=(15,5))

"""Checking for Missing and Duplicate Values"""

df.duplicated().sum()

df.isnull().sum()

"""

# 🔍 2) Distribution & General Overview
"""

#Employee count per department

plt.figure(figsize=(8,5))
sns.countplot(data=df, x='Department')
plt.title("Employees per Department")
plt.xticks(rotation=20)
plt.ylabel('')
plt.show()

#Attrition rate (Yes vs No)

plt.figure(figsize=(6,6))
df['Attrition'].value_counts().plot.pie(autopct='%1.0f%%')
plt.title("Employee Attrition Rate")
plt.ylabel('')
plt.show()

"""# 🏢 3) Department Analysis"""

#Departments with the highest attrition
departments = df['Department'].unique()
stayed = df[df['Attrition']=='No']['Department'].value_counts().reindex(departments, fill_value=0)
left = df[df['Attrition']=='Yes']['Department'].value_counts().reindex(departments, fill_value=0)

fig, ax = plt.subplots(figsize=(8,5))
ax.barh(departments, stayed, color='skyblue', label='Stayed')
ax.barh(departments, -left, color='salmon', label='Left')  # negative for left side
ax.set_xlabel("Number of Employees")
ax.set_title("Attrition by Department (Population Pyramid)")
ax.legend()
plt.show()

#14% of R&D , 21% of Sales , 19% of HR

##Monthly income distribution by department (Boxplot)
plt.figure(figsize=(10,5))
sns.violinplot(data=df, x='Department', y='MonthlyIncome',inner='box')
plt.title("Monthly Income Distribution by Department")
plt.xticks(rotation=25)
plt.show()

#Average tenure of employees who left (per department)

plt.figure(figsize=(8,5))
df[df['Attrition']=='Yes'].groupby('Department')['YearsAtCompany'].mean().sort_values().plot(kind='bar')
plt.title("Average Tenure of Employees Who Left (by Department)")
plt.ylabel("Years")
plt.xticks(rotation=25)
plt.show()

"""
# 💰 4) Income Analysis (Attrition by Income Range)"""

#Attrition distribution by income brackets

left = df[df['Attrition'] == 'Yes'].copy()

bins = [0,3000,6000,9000,12000,15000,18000]
labels = ['0-3k','3-6k','6-9k','9-12k','12-15k','15-18k']
left['IncomeRange'] = pd.cut(left['MonthlyIncome'], bins=bins, labels=labels)

plt.figure(figsize=(8,5))
left['IncomeRange'].value_counts().sort_index().plot(kind='line', marker='o')
plt.title("Attrition by Monthly Income Range")
plt.xlabel("Income Range")
plt.ylabel("Count")
plt.show()

"""

# 📅 5) Tenure Analysis (YearsAtCompany)"""

#Years at company for employees who left

plt.figure(figsize=(8,5))
df[df['Attrition']=='Yes']['YearsAtCompany'].plot.hist(bins=15)
plt.title("Years at Company — Employees Who Left")
plt.xlabel("Years")
plt.ylabel("Count")
plt.show()

"""# 👔 6) Job Role Analysis"""

#Job roles with the highest attrition

plt.figure(figsize=(10,5))
sns.countplot(data=df[df['Attrition']=='Yes'], x='JobRole')
plt.title("Attrition by Job Role")
plt.xticks(rotation=35)
plt.ylabel('')
plt.show()

"""
# 🔥 7) Correlation Analysis"""

#Heatmap for Age, Income, and Tenure

plt.figure(figsize=(8,5))
sns.heatmap(df[['Age','MonthlyIncome','YearsAtCompany']].corr(), annot=True)
plt.title("Correlation Heatmap (Age, Income, Tenure)")
plt.show()

"""# 📊 Key Insights from the HR Attrition Dataset

### 1. Departments with the highest attrition
- The HR and R&D departments show the highest attrition rates.
- This indicates potential internal issues such as workload, job satisfaction, or compensation gaps within these departments.

---

### 2. Low salary is a major driver of attrition
- Employees who left the company tend to have significantly lower monthly incomes.
- This pattern appears consistently across departments, making salary one of the strongest predictors of attrition.

---

### 3. Sales department characteristics
- The Sales department has a large employee count, similar to R&D.
- Employees in Sales who left the company often had longer years of experience.
- This suggests they may have received better job offers elsewhere due to their skill level and experience.

---

### 4. Job roles with the highest attrition
- The Laboratory Technician role shows one of the highest exit rates.
- This group also falls into the lower-income range, reinforcing the role of salary in attrition behavior.

---

### 5. Employees with fewer years at the company tend to leave more
- A significant number of employees who left had short tenure.
- This may indicate difficulty in early-stage engagement, onboarding quality, or lack of job fit, causing employees to leave before settling.

---

### 🔍 Overall Conclusion
- Low income is the strongest and most consistent factor related to employee attrition.
- Department culture, experience level, and early career engagement also play major roles.
- Improving compensation, onboarding, and (department-level conditions)—especially in HR and R&D—may help reduce turnover.


"""

